name: Danger JS
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Danger
        run: npx danger ci
        env:
          DANGER_GITHUB_API_TOKEN: ${{secrets.DANGER_GITHUB_API_TOKEN}}
          DANGER_DISABLE_TRANSPILATION: true
      
